### PR TITLE
Handling lost media

### LINKED ISSUE #168: Handeling lost media-files
1) When a media (video or image) is lost (ex. moved) you should be able to point it out so all tags,bookmarks etc. start to work again.

2) When hovering over a media file the project tree a tool tip shold be shown with the whole path to the file.

3) When loading a saved project the program checks all links for missing media. It should be made possible to correct all missing links.

4) Possible to view all files and their paths imported in the project from menu selection

### PR DESCRIPTION
**Pull request by henpe071**
Added a dialog found in file menu where the user can change the paths for the videos in the project.
This dialog will show all video in the project and their paths. It will also show if they can be read. This will let the user know if a file might have been moved.

The dialog have 3 button. 
* A button for opening the folder where the selected item should be. (The path that is currently shown).
* A button for selecting a new path for a video.
* A button for updating the path to the video.

The second button will update the whole path and the video name and the third button will only let the user select a new folder where the video should be. This will keep the video name the same. 

Clicking ok will store these changed while cancel will just discard them.

Also added the path on a tool tip when hovering over a videoitem.

When trying to load a video which can't be loaded the user will be prompted with a dialog where they can enter a new path for the video and try to load again. This will update the video path.

Fixes #168

### CODE REVIEW

**Comment by niklasniklas** [comment]
Issue: Does not show newly added videos to the project.  Also the list is not cleared if New project is chosen.
They show if I save the project and open it again.

**Comment by niklasniklas** [comment]
Some issues:
* If video is missing media, and you press "Cancel" i "Where is ..." -dialog, and thereafter select an analysis under video with missing media, you get unexpected behaviour
* Current selected video is still playable if you redirect the path in View path dialog, only get "where is ..." after you deselect video and reselect it

**Comment by niklasniklas** [comment]
Features
* Add button in "where is ..." dialog to open "View paths" dialog
* Check all media at start up. If problem open "View paths" dialog

**Comment by niklasniklas** [comment]
Temporary project
Send black frame to frameprocessor
Send a call to frameprocessor after viewpath dialog

**Comment by henpe071** [comment]
Update icon in project tree

**Comment by niklasniklas** [comment]
Issue when deleting many items i project tree.
When deleting several items in project tree and one of the selected has not been identified by the program that media is missing -> the program crasches.
Test case:
* Add three videos
* Select new and wrong path to the videos
* select the last one (press cancel i dialog)
* Hold shift
* Select the first item (press cancel)
* Press delete
* the program crasches when deleting the middle item

**Comment by niklasniklas** [comment]
Feature:
replace video thumnail with lost media with this icon:
1471539067_minus-sign red

**Pull request merged**
