### PR TITLE
Ana widget + yolo

### PR DESCRIPTION
**Pull request by henpe071**
Added yolo analysis as object detection and a new widget for a better overlook of the analysis.

Updated the rest of the program to work with two different kinds of analysis and made some small QoL changes for clarity.

Removed some old files that are no longer needed.

### CODE REVIEW

**Comment by niklasniklas** [comment]
When saving an object detection, only the start of each interval is saved
Test case: 

- Run an object detection
- If you have multiple detections in a row you get a solid yellow marking on timeline, but in Yolo widget you get all frames from the detections in dropdown list
- when project is saved and reloaded only the start of each "yellow interval" is loaded i yolo-dropdown

**Comment by niklasniklas** [comment]
Crasches when opening "Object detection settings." and pressing OK.

**Comment by henpe071** [comment]
Pushed up what I've made currently if you want to try it out.
Note: Motion detection will currently crash the object detection widget if tried to open.

**Comment by niklasniklas** [comment]
Settings changed in Object detection settings does not get "saved". If I change settings the settings are changed but when I open the settingsdialog the default values are shown. THis only applies to network size or sample freq

**Comment by niklasniklas** [comment]
"End frame numer" (to the right of the timeslider at the bottom) i Yolowidget is not always initialized properly when opening Yolowidget

**Comment by niklasniklas** [comment]
Two thigs for Object detecton widget:
* A checkbox for automatically update videoplayer if checked (and not update if unchecked). Default unchecked
* It is enough with "heltal" for confidence under each thumbnail

**Comment by niklasniklas** [comment]
Change default: Menue: Video analysis->Analysis input should be checked by default.

**Comment by niklasniklas** [comment]
Sometimes, when I change sample freq for object detection (for example 0.2 or 0.1 when I have 29 fps on video) every frame is analyzied. The rounding to of the specified sample frequency does not seem to work all the time...

**Comment by niklasniklas** [comment]
Great improvements!

**Pull request merged**
